package telasAlteraveis;

/**
 * @author : Davidson Teixeira & Lucas Cavalcante
 * @year : 04/2023
 */

public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMCads = new javax.swing.JMenu();
        jMIFuncionario = new javax.swing.JMenuItem();
        jMICliente = new javax.swing.JMenuItem();
        jMIProduto = new javax.swing.JMenuItem();
        jMILogout = new javax.swing.JMenuItem();
        jMEfetuar = new javax.swing.JMenu();
        jMIVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMCads.setText("Cadastros");

        jMIFuncionario.setText("Funcionário");
        jMIFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFuncionarioActionPerformed(evt);
            }
        });
        jMCads.add(jMIFuncionario);

        jMICliente.setText("Cliente");
        jMICliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIClienteActionPerformed(evt);
            }
        });
        jMCads.add(jMICliente);

        jMIProduto.setText("Produto");
        jMIProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProdutoActionPerformed(evt);
            }
        });
        jMCads.add(jMIProduto);

        jMILogout.setText("Log out");
        jMILogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILogoutActionPerformed(evt);
            }
        });
        jMCads.add(jMILogout);

        jMenuBar.add(jMCads);

        jMEfetuar.setText("Efetuar");

        jMIVenda.setText("Venda");
        jMEfetuar.add(jMIVenda);

        jMenuBar.add(jMEfetuar);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFuncionarioActionPerformed
        dispose();
        telaCadastroFuncionario screen = new telaCadastroFuncionario();
        screen.setVisible(true);
    }//GEN-LAST:event_jMIFuncionarioActionPerformed

    private void jMIProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProdutoActionPerformed
        dispose();
        telaCadastroFuncionario screen = new telaCadastroFuncionario();
        screen.setVisible(true);
    }//GEN-LAST:event_jMIProdutoActionPerformed

    private void jMIClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIClienteActionPerformed
        dispose();
        //telaMonitor screen = new telaMonitor();
        //screen.setVisible(true);
    }//GEN-LAST:event_jMIClienteActionPerformed

    private void jMILogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILogoutActionPerformed
        dispose();
        telaLogin screen = new telaLogin();
        screen.setVisible(true);
    }//GEN-LAST:event_jMILogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new telaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMCads;
    private javax.swing.JMenu jMEfetuar;
    private javax.swing.JMenuItem jMICliente;
    private javax.swing.JMenuItem jMIFuncionario;
    private javax.swing.JMenuItem jMILogout;
    private javax.swing.JMenuItem jMIProduto;
    private javax.swing.JMenuItem jMIVenda;
    private javax.swing.JMenuBar jMenuBar;
    // End of variables declaration//GEN-END:variables
}
